version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - ./frontend/.env
    environment:
      - ENV=docker
    ports:
      - "4173:4173"

  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - ENV=docker
    networks:
      - app-network
    depends_on:
      - mongodb
    ports:
      - "4000:4000"


  mongodb:
    image: mongo:7.0
    volumes:
      - db-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
