version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    networks:
      - app-network

  mongodb:
    image: mongo:7-alpine
    volumes:
      - db-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
